os:
    - linux
    - osx
language: node_js
node_js:
    - "stable"
    - "0.12"
    - "0.11"
    - "0.10"
    - "iojs"
branches:
    only:
        - master
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq debhelper autotools-dev cups-ppdc libcups2-dev cups imagemagick ghostscript
script: npm test
